# This is the configuration file for the STS server

[server]
port = 80

[database]
name = "sts_db"
username = "ST_server_"
passwordFile = "secrets/db_pass"
host = "localhost"

[messageQueue]
# monitorReloadTime is the time in milliseconds
# between each check for new messages
monitorReloadTime = 3000

