# This is the configuration file for the STS server

[server]
port = 80

[database]
name = "sts_db"
username = "ST_server"
host = "192.168.80.1"

[messageQueue]
# monitorReloadTime is the time in milliseconds
# between each check for new messages
monitorReloadTime = 3000

